"""
Speculate .pf Exporter
======================
Single-file exporter that reads a Sirocco .pf template, computes all
grid-specific derived physics, and writes a valid .pf file ready for
use with Sirocco.

Supports three grid families:
    - CV no-boundary-layer  (speculate_cv_no-bl_*)
    - CV boundary-layer     (speculate_cv_bl_*)
    - AGN                   (speculate_agn_*)

Each grid type stores parameters in emulator space which may differ from
the physical Sirocco units.  This module applies the necessary physics
conversions (e.g. boundary-layer luminosity from a disk-luminosity
fraction, QSOSED SED generation for AGN grids, R_g-scaled quantities).

Usage (called from speculate_benchmark.export_pf_template):
    from exports.templates.speculate_pf_exporter import write_pf

    write_pf(
        grid_name="speculate_cv_bl_grid_v87f",
        physical_params={"Disk.mdot(msol/yr)": 1e-8, ...},
        output_path="exports/my_export.pf",
        header_lines=["### Generated by Speculate", ...],
    )
"""

import logging
import os
import sys
import warnings
from math import pi
from pathlib import Path
from typing import Dict, List, Optional, Sequence

import numpy as np

log = logging.getLogger(__name__)

# Directory containing the .pf template files (same folder as this script)
_TEMPLATE_DIR = Path(__file__).resolve().parent

# ======================================================================
# Physical Constants (CGS)
# ======================================================================
_MSOL = 1.989e33          # g
_YR = 3.1556925e7         # s
_GRAV_CONST = 6.67e-8     # cm³ g⁻¹ s⁻²
_STEFAN_BOLTZMANN = 5.6696e-5  # erg cm⁻² s⁻¹ K⁻⁴
_C = 2.99792458e10        # cm/s
_EDD_LUMINOSITY_CONST = 1.39e38  # erg/s per Msol


# ======================================================================
# Template Selection
# ======================================================================

_TEMPLATE_MAP = {
    "cv_no-bl": "speculate_cv_no-bl_v87f_template.pf",
    "cv_no_bl": "speculate_cv_no-bl_v87f_template.pf",
    "cv_bl":    "speculate_cv_bl_v87f_template.pf",
    "agn":      "speculate_agn_v1.3_template.pf",
}


def _detect_grid_type(grid_name: str) -> str:
    """Return a canonical grid type key: 'cv_no-bl', 'cv_bl', or 'agn'."""
    lower = grid_name.lower()
    if "cv_no-bl" in lower or "cv_no_bl" in lower:
        return "cv_no-bl"
    elif "cv_bl" in lower or "cv" in lower:
        return "cv_bl"
    elif "agn" in lower:
        return "agn"
    raise ValueError(
        f"Cannot determine grid type for '{grid_name}'. "
        f"Expected a name containing one of: cv_no-bl, cv_bl, agn"
    )


def _resolve_template(grid_name: str) -> Path:
    """Return the path to the template .pf file for the given grid name."""
    grid_type = _detect_grid_type(grid_name)
    template_path = _TEMPLATE_DIR / _TEMPLATE_MAP[grid_type]
    if not template_path.exists():
        raise FileNotFoundError(f"Template not found: {template_path}")
    return template_path


# ======================================================================
# .pf Reader / Writer
# ======================================================================

def _read_pf(path: Path) -> List[str]:
    """Read a .pf file and return its lines (preserving order)."""
    with open(path, "r") as f:
        return f.readlines()


def _read_pf_as_dict(path: Path) -> Dict[str, str]:
    """Parse a .pf template into a {key: value_string} dict."""
    result = {}
    for line in _read_pf(path):
        key = _parse_key(line)
        if key is not None:
            tokens = line.strip().split()
            if len(tokens) >= 2:
                result[key] = tokens[-1]
    return result


def _parse_key(line: str) -> Optional[str]:
    """Extract the parameter key from a .pf line, or None for comments/blanks."""
    stripped = line.strip()
    if not stripped or stripped.startswith("#"):
        return None
    return stripped.split()[0]


def _format_value(value, key: str = "") -> str:
    """Format a numeric value for .pf output, matching Sirocco conventions."""
    if isinstance(value, str):
        return value
    if abs(value) >= 1e6 or (abs(value) < 1e-3 and value != 0):
        return f"{value:.6e}"
    return f"{value:g}"


def _replace_value_in_line(line: str, new_value: str) -> str:
    """Replace the value portion of a key-value .pf line, preserving alignment."""
    stripped = line.rstrip("\n")
    tokens = stripped.split()
    if len(tokens) < 2:
        return line
    val_start = stripped.rfind(tokens[-1])
    padding = stripped[:val_start]
    return f"{padding}{new_value}\n"


# ======================================================================
# Grid-Specific Derived Physics
# ======================================================================

def _postprocess_cv_bl(params: Dict[str, float], template_path: Path) -> Dict[str, float]:
    """
    Convert CV boundary-layer emulator-space values to physical Sirocco units.

    In the emulator:
        - Boundary_layer.luminosity(ergs/s) is stored as a *fraction of L_disk*
          where L_disk = G * M_star * Mdot_disk / (2 * R_star).
        - Boundary_layer.temp(K) is stored as H/R_wd (boundary-layer height
          fraction), converted to temperature via Stefan-Boltzmann.
    """
    bl_lum_key = "Boundary_layer.luminosity(ergs/s)"
    bl_temp_key = "Boundary_layer.temp(K)"

    if bl_lum_key not in params and bl_temp_key not in params:
        return params

    # Read fixed stellar parameters from the template
    tpl = _read_pf_as_dict(template_path)
    M_star_msol = float(tpl["Central_object.mass(msol)"])
    R_star_cm = float(tpl["Central_object.radius(cm)"])

    # Disk accretion luminosity: L_disk = G * M_star * Mdot_disk / (2 * R_star)
    disk_mdot = params.get("Disk.mdot(msol/yr)", float(tpl["Disk.mdot(msol/yr)"]))
    disk_mdot_cgs = disk_mdot * _MSOL / _YR  # g/s
    L_disk = _GRAV_CONST * (M_star_msol * _MSOL) * disk_mdot_cgs / (2.0 * R_star_cm)

    # BL luminosity: emulator stores fraction of L_disk
    if bl_lum_key in params:
        bl_frac = params[bl_lum_key]
        params[bl_lum_key] = bl_frac * L_disk

    # BL temperature: emulator stores H/R_wd (area fraction)
    # Area of BL spherical segment = 4 * pi * R_star^2 * (H/R_wd)
    # Stefan-Boltzmann: T = (L / (area * sigma))^0.25
    if bl_temp_key in params and bl_lum_key in params:
        h_over_r = params[bl_temp_key]
        bl_luminosity = params[bl_lum_key]
        area = 4.0 * pi * R_star_cm**2 * h_over_r
        if area > 0 and bl_luminosity > 0:
            params[bl_temp_key] = (bl_luminosity / (area * _STEFAN_BOLTZMANN)) ** 0.25
        else:
            params[bl_temp_key] = 0.0

    return params


def _postprocess_agn(params: Dict[str, float], template_path: Path,
                     output_dir: str) -> Dict[str, float]:
    """
    Compute AGN-specific derived quantities from emulator parameters.

    The AGN grid stores several parameters in scaled units:
        - Disk.mdot as a fraction of Mdot_Eddington
        - Wind.mdot as a fraction of Disk.mdot (already handled by emulator_to_physical)
        - KWD.acceleration_length as a multiplier of R_g

    Derived "fixed" parameters that depend on mass:
        - Central_object.radius(cm) = 6 * R_g  (ISCO for Schwarzschild)
        - KWD.rmin = 10 rstar  (60 R_g)
        - KWD.rmax = 100 rstar (600 R_g)
        - Wind.radmax(cm) = 600,000 * R_g
        - Disk.radmax(cm) from QSOSED self-gravity radius
        - Central_object.luminosity(ergs/s) from QSOSED 2-10 keV integration
        - Input_spectra.model_file from generated QSOSED SED
    """
    mass_key = "Central_object.mass(msol)"
    if mass_key not in params:
        log.warning("AGN export: no Central_object.mass found — skipping derived physics")
        return params

    mass_msol = params[mass_key]
    Rg = (_GRAV_CONST * mass_msol * _MSOL) / _C**2

    # Derived geometric parameters
    params["Central_object.radius(cm)"] = 6.0 * Rg
    params["KWD.rmin(in_units_of_rstar)"] = 10.0
    params["KWD.rmax(in_units_of_rstar)"] = 100.0
    params["Wind.radmax(cm)"] = 600_000.0 * Rg

    # Disk mdot: convert from Eddington fraction to Msol/yr
    disk_mdot_key = "Disk.mdot(msol/yr)"
    if disk_mdot_key in params:
        disk_mdot_msolyr = params[disk_mdot_key]
    else:
        tpl = _read_pf_as_dict(template_path)
        disk_mdot_msolyr = float(tpl.get(disk_mdot_key, 1e-8))

    # Recover Eddington fraction for QSOSED log_mdot
    L_edd = _EDD_LUMINOSITY_CONST * mass_msol
    r_isco = 6.0
    eta = 1.0 - np.sqrt(1.0 - 2.0 / (3.0 * r_isco))
    mdot_edd_cgs = L_edd / (eta * _C**2)
    mdot_edd_msolyr = (mdot_edd_cgs / _MSOL) * _YR
    edd_fraction = disk_mdot_msolyr / mdot_edd_msolyr
    log_mdot = np.log10(edd_fraction)

    # Generate QSOSED SED
    sed_filename, L_xray, r_out_Rg = _generate_qsosed(
        mass_msol, log_mdot, output_dir
    )

    if sed_filename is not None:
        params["Input_spectra.model_file"] = sed_filename
        params["Central_object.luminosity(ergs/s)"] = L_xray
        params["Disk.radmax(cm)"] = r_out_Rg * Rg

    return params


def _generate_qsosed(mass_msol: float, log_mdot: float,
                     output_dir: str):
    """
    Generate a QSOSED SED model and write the .dat/.ls files Sirocco needs.

    Returns (sed_ls_filename, L_xray_2_10keV, r_out_Rg) or (None, None, None)
    on failure.
    """
    # Add pyQSOSED to the import path
    pyqsosed_dir = str(_TEMPLATE_DIR / "pyQSOSED")
    if pyqsosed_dir not in sys.path:
        sys.path.insert(0, pyqsosed_dir)

    try:
        from pyqsosed import qsosed
    except ImportError as e:
        log.error(f"Cannot import pyQSOSED: {e}")
        return None, None, None

    sed_base = f"qsosed_M{mass_msol:.2e}_mdot{log_mdot:.3f}"
    sed_dat = os.path.join(output_dir, f"{sed_base}.dat")
    sed_ls = os.path.join(output_dir, f"{sed_base}.ls")

    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            qso = qsosed(M=mass_msol, dist=1.0e-4, log_mdot=log_mdot,
                          a=0, cos_inc=0.5, fcol=1, z=0)

        try:
            qso.set_units('cgs_wave')
        except Exception:
            pass

        L_lambda = qso.get_SED(as_flux=False)
        wave = qso.wave_grid  # Angstroms

        # Sort wavelength ascending (short → long)
        sort_idx = np.argsort(wave)
        sorted_wave = wave[sort_idx]
        sorted_Llambda = L_lambda[sort_idx]

        # High-energy cut at ~100 keV (0.124 Å)
        mask = sorted_wave >= 1.239842e-1
        sorted_wave = sorted_wave[mask]
        sorted_Llambda = sorted_Llambda[mask]

        # Floor zeros for Sirocco log-interpolation safety
        sorted_Llambda = np.maximum(sorted_Llambda, 1e-40)

        # Write SED data file
        os.makedirs(output_dir, exist_ok=True)
        np.savetxt(sed_dat,
                   np.column_stack((sorted_wave, sorted_Llambda)),
                   fmt='%.6e', delimiter='\t')

        # Write .ls pointer file (Sirocco convention)
        with open(sed_ls, 'w') as f:
            f.write(f"{os.path.basename(sed_dat)} -1")

        # 2-10 keV X-ray luminosity (1.24–6.2 Å)
        mask_xray = (sorted_wave >= 1.24) & (sorted_wave <= 6.2)
        if np.sum(mask_xray) > 1:
            L_xray = float(np.trapz(sorted_Llambda[mask_xray],
                                    sorted_wave[mask_xray]))
        else:
            L_xray = 1e40
            log.warning("Poor X-ray sampling in QSOSED — using fallback luminosity")

        r_out_Rg = max(float(qso.r_out), 60_000.0)

        log.info(f"Generated QSOSED: {sed_ls} "
                 f"(M={mass_msol:.1e}, log_mdot={log_mdot:.2f}, "
                 f"Lx={L_xray:.2e}, Rout={r_out_Rg:.0f}Rg)")

        # Return paths relative to output_dir for portability in .pf
        return os.path.basename(sed_ls), L_xray, r_out_Rg

    except Exception as e:
        log.error(f"QSOSED generation failed: {e}")
        return None, None, None


# ======================================================================
# Main Export Function
# ======================================================================

def write_pf(
    grid_name: str,
    physical_params: Dict[str, float],
    output_path: str,
    header_lines: Optional[List[str]] = None,
    observer_angles: Optional[Sequence[float]] = None,
):
    """
    Write a valid Sirocco .pf file by updating a template with fitted values.

    Applies grid-specific derived physics before writing:
        - **CV no-BL**: direct parameter substitution (all conversions done
          by ``emulator_to_physical``).
        - **CV BL**: converts boundary-layer luminosity from L_disk fraction
          and temperature from H/R_wd via Stefan-Boltzmann.
        - **AGN**: computes R_g-scaled geometry, generates a QSOSED SED model,
          and sets X-ray luminosity and disk extent.

    Parameters
    ----------
    grid_name : str
        The grid identifier (e.g. ``speculate_cv_bl_grid_v87f``).
    physical_params : dict
        Sirocco parameter keywords → values from ``emulator_to_physical``.
    output_path : str
        Destination path for the exported .pf file.
    header_lines : list of str, optional
        ``###``-prefixed comment lines to prepend as a metadata header.
    observer_angles : list of float, optional
        If provided, replace the template's ``Spectrum.angle(0=pole)`` entries
        and update ``Spectrum.no_observers`` to match. ``Spectrum_cycles`` is
        intentionally left unchanged.
    """
    grid_type = _detect_grid_type(grid_name)
    template_path = _resolve_template(grid_name)
    template_lines = _read_pf(template_path)

    # Apply grid-specific derived physics
    params = dict(physical_params)
    output_dir = os.path.dirname(output_path) or "."

    if grid_type == "cv_bl":
        params = _postprocess_cv_bl(params, template_path)
    elif grid_type == "agn":
        params = _postprocess_agn(params, template_path, output_dir)

    # Build lookup of parameters to update; strip Inclination (not a .pf key)
    remaining = {k: v for k, v in params.items() if k != "Inclination"}

    output = []

    # Prepend the Speculate metadata header
    if header_lines:
        for hl in header_lines:
            output.append(hl if hl.endswith("\n") else hl + "\n")
        output.append("\n")

    # For AGN, Input_spectra.model_file appears twice in the template
    # (once for wind, once for final spectrum).  We track how many times
    # we've seen it to ensure both instances are updated.
    sed_file = remaining.pop("Input_spectra.model_file", None)
    observer_angles = [] if observer_angles is None else list(observer_angles)
    updated_no_observers = False
    wrote_observer_angles = False

    for line in template_lines:
        key = _parse_key(line)
        if observer_angles and key == "Spectrum.no_observers":
            output.append(_replace_value_in_line(line, _format_value(len(observer_angles), key)))
            updated_no_observers = True
        elif observer_angles and key == "Spectrum.angle(0=pole)":
            if not wrote_observer_angles:
                for angle in observer_angles:
                    output.append(_replace_value_in_line(line, _format_value(float(angle), key)))
                wrote_observer_angles = True
        elif key is not None and key in remaining:
            new_val = _format_value(remaining.pop(key), key)
            output.append(_replace_value_in_line(line, new_val))
        elif key == "Input_spectra.model_file" and sed_file is not None:
            # Update every occurrence of Input_spectra.model_file
            output.append(_replace_value_in_line(line, sed_file))
        else:
            output.append(line)

    if observer_angles and not updated_no_observers:
        raise ValueError(
            f"Template '{template_path.name}' has no Spectrum.no_observers line "
            "to update for custom observer angles."
        )
    if observer_angles and not wrote_observer_angles:
        raise ValueError(
            f"Template '{template_path.name}' has no Spectrum.angle(0=pole) line "
            "to replace with custom observer angles."
        )

    for leftover_key in remaining:
        log.warning(
            f"Parameter '{leftover_key}' not found in template "
            f"'{template_path.name}' — skipped."
        )

    os.makedirs(output_dir, exist_ok=True)
    with open(output_path, "w") as f:
        f.writelines(output)

    log.info(f"Exported Sirocco .pf file to {output_path}")
